---
# Role for fix_repo_check_ptf_group
# Get the latest PTF group information from PSP(Preventive Service Planning) server, and check if the latest PTF group is already
# in ptf_group_image table or already downloading.
- name: Initialize check_ptf_group_fail
  ansible.builtin.set_fact:
    check_ptf_group_fail: false

- name: Check and get the latest PTF group information on PSP
  ibm.power_ibmi.ibmi_fix_group_check:
    groups: '{{ ptf_group }}'
  register: fix_group_check_result

- name: Print the latest PTF group information
  ansible.builtin.debug:
    var: fix_group_check_result

- name: Check for failure
  when: fix_group_check_result.group_info is not defined
  block:
    - name: If cannot get the latest PTF group information, then fail
      ansible.builtin.debug:
        msg: "Get the latest PTF group information fail, skip the rest of this role"

    - name: Set check_ptf_group_fail to True
      ansible.builtin.set_fact:
        check_ptf_group_fail: true

- name: Perform checking
  when: fix_group_check_result.group_info is defined
  block:
    - name: Check if PTF group information is already in catalog's PTF group information table
      ibm.power_ibmi.ibmi_fix_repo:
        type: "ptf_group"
        action: "find"
        parameters:
          - "{{ {'ptf_group_number': fix_group_check_result.group_info[0].ptf_group_number,
          'ptf_group_level': fix_group_check_result.group_info[0].ptf_group_level,
          'release_date': fix_group_check_result.group_info[0].release_date} }}"
      register: ptf_group_find_result
      when: fix_group_check_result.group_info != []

    - name: Print find PTF group result
      ansible.builtin.debug:
        var: ptf_group_find_result

    - name: Checking download status table
      when: ptf_group_find_result.fail_list is defined
      block:
        - name: Check if PTF group information is already in catalog's download_status table, which means PTF group is downloading.
          ibm.power_ibmi.ibmi_fix_repo:
            type: "download_status"
            action: "find"
            parameters:
              - "{{ {'ptf_group_number': fix_group_check_result.group_info[0].ptf_group_number,
              'ptf_group_level': fix_group_check_result.group_info[0].ptf_group_level,
              'release_date': fix_group_check_result.group_info[0].release_date} }}"
          register: download_status_find_result
          when: fix_group_check_result.group_info != []

        - name: Print find download_status table result
          ansible.builtin.debug:
            var: download_status_find_result
