---
# Role for sync_apply_individual_ptfs_local
- name: Initialize various lists
  ansible.builtin.set_fact:
    savefile_list: []
    coverletter_list: []
    dest_file_list: []

# Assumption is that both the save file and associated cover letter are downloaded to a common source directory
# on the local host such as with module ibmi_download_fix_from_cloud.
# The save files are typically copied to the QGPL library on the target IBM i (default location), but another
# library may be designated. The cover letter is transferred as a member of QAPZCOVER.FILE in GPL library.
# The sync'ed files are expected to have the following file name format:
#     Save file destination (GPL library example): /QSYS.LIB/QGPL.LIB/Q<ptf_id>.FILE
#     Cover letter is a member of QAPZCOVER.FILE in QGPL at: /QSYS.LIB/QGPL.LIB/QAPZCOVER.FILE/Q<ptf_id>.MBR

- name: Compose savefile list and coverletter list for copying the files
  ansible.builtin.set_fact:
    savefile_list: >-
      {{ savefile_list | default([]) +
      [[not_loaded_list_var.file_path, not_loaded_list_var.file_name] |
      ansible.builtin.path_join] }}
    coverletter_list: >-
      {{ coverletter_list | default([]) +
      [not_loaded_list_var | combine({'src': [not_loaded_list_var.file_path,
      not_loaded_list_var.file_name | ansible.builtin.splitext | first + '.MBR'] |
      ansible.builtin.path_join})] }}
  loop: "{{ sync_apply_individual_ptfs_local_not_loaded_list }}"
  loop_control:
    loop_var: not_loaded_list_var

# Local transfer of save files and cover letters to IBM i target(s)

- name: Transfer PTF savfs to target IBM i system
  ibm.power_ibmi.ibmi_copy:
    src: "{{ savefile }}"
    lib_name: "{{ (sync_apply_individual_ptfs_local_dest | basename | splitext)[0] }}"
    force: true
  loop: "{{ savefile_list }}"
  loop_control:
    loop_var: savefile
  ignore_errors: true
  register: ibmi_copy_savefile_results

- name: Transfer PTFs' cover letter to target IBM i system as member of QAPZCOVER.FILE
  ibm.power_ibmi.ibmi_synchronize_files:
    dest: "/QSYS.LIB/QGPL.LIB/QAPZCOVER.FILE"
    src_list: "{{ coverletter_list }}"
  when: coverletter_list != []
  delegate_to: localhost
  ignore_errors: true
  register: sync_coverletter_result

# Generate arguments for loading and applying PTFs

- name: Initialize sync savf lists
  ansible.builtin.set_fact:
    sync_apply_individual_ptfs_local_sync_success_list: []
    sync_apply_individual_ptfs_local_sync_fail_list: []

- name: Compose sync savf success list
  ansible.builtin.set_fact:
    sync_apply_individual_ptfs_local_sync_success_list: >-
      {{ sync_apply_individual_ptfs_local_sync_success_list |
      default([]) + [sync_apply_individual_ptfs_local_not_loaded_list[index]] }}
  when: item.rc == 0
  loop: "{{ ibmi_copy_savefile_results.results }}"
  loop_control:
    index_var: index

- name: Compose sync savf failure list
  ansible.builtin.set_fact:
    sync_apply_individual_ptfs_local_sync_fail_list: >-
      {{ sync_apply_individual_ptfs_local_sync_fail_list |
      default([]) + [sync_apply_individual_ptfs_local_not_loaded_list[index]] }}
  when: item.rc != 0
  loop: "{{ ibmi_copy_savefile_results.results }}"
  loop_control:
    index_var: index

- name: Compose sync coverletter result lists (for debug)
  ansible.builtin.set_fact:
    sync_coverletter_success_list: "{{ sync_coverletter_result.success_list | default([]) }}"
    sync_coverletter_fail_list: "{{ sync_coverletter_result.fail_list | default([]) }}"

- name: Print the list of successful sync
  ansible.builtin.debug:
    var: sync_apply_individual_ptfs_local_sync_success_list

- name: Print the list of failed sync
  ansible.builtin.debug:
    var: sync_apply_individual_ptfs_local_sync_fail_list

- name: Print the list of successful coverletter sync
  ansible.builtin.debug:
    var: sync_coverletter_success_list

- name: Print the list of failed coverletter sync
  ansible.builtin.debug:
    var: sync_coverletter_fail_list

- name: Include load_apply_ptfs role to load and apply ptfs
  ansible.builtin.include_role:
    name: load_apply_ptfs
  vars:
    load_apply_ptfs_to_be_loaded_ptf_list: "{{ sync_apply_individual_ptfs_local_sync_success_list }}"
    load_apply_ptfs_remote_lib: "{{ (sync_apply_individual_ptfs_local_dest | basename | splitext)[0] }}"
    load_apply_ptfs_loaded_list: "{{ sync_apply_individual_ptfs_local_already_loaded_list }}"
    load_apply_ptfs_apply_all_loaded_ptf: "{{ sync_apply_individual_ptfs_local_apply_all_loaded_ptf }}"
    load_apply_ptfs_temp_or_perm: "{{ sync_apply_individual_ptfs_local_temp_or_perm }}"
    load_apply_ptfs_delayed_option: "{{ sync_apply_individual_ptfs_local_delayed_option }}"
    load_apply_ptfs_auto_ipl: "{{ sync_apply_individual_ptfs_local_auto_ipl }}"
  # We want to call this even if a noop (nothing to load or loaded) to ensure the load_apply_ptfs
  # return variables are initialized for assignment in the next task.

- name: Set role return variables from load_apply_ptfs role results
  ansible.builtin.set_fact:
    sync_apply_individual_ptfs_local_load_success_list: "{{ load_apply_ptfs_load_success_list | default([]) }}"
    sync_apply_individual_ptfs_local_load_fail_list: "{{ load_apply_ptfs_load_fail_list | default([]) }}"
    sync_apply_individual_ptfs_local_load_fail_dict: "{{ load_apply_ptfs_load_fail_dict | default([]) }}"
    sync_apply_individual_ptfs_local_apply_fail_with_requisite_list: >-
      {{ load_apply_ptfs_apply_fail_with_requisite_list | default([]) }}
    sync_apply_individual_ptfs_local_apply_fail_dict: "{{ load_apply_ptfs_apply_fail_dict | default([]) }}"
    sync_apply_individual_ptfs_local_requisite_list: "{{ load_apply_ptfs_requisite_list | default([]) }}"
    sync_apply_individual_ptfs_local_apply_success_list: "{{ load_apply_ptfs_apply_success_list | default([]) }}"
    sync_apply_individual_ptfs_local_apply_fail_list: "{{ load_apply_ptfs_apply_fail_list | default([]) }}"

- name: Perform clean up actions
  when: sync_apply_individual_ptfs_local_delete | bool and sync_apply_individual_ptfs_local_sync_success_list != []
  block:
    - name: Compose dest file path
      ansible.builtin.set_fact:
        dest_file_list: >-
          {{ dest_file_list | default([]) +
          [[sync_apply_individual_ptfs_local_dest, sync_success_list_var.file_name] |
          ansible.builtin.path_join] }}
      loop: "{{ sync_apply_individual_ptfs_local_sync_success_list }}"
      loop_control:
        loop_var: sync_success_list_var

    - name: Print the list of dest file path
      ansible.builtin.debug:
        var: dest_file_list

    - name: Delete the dest file
      ansible.builtin.file:
        path: "{{ dest_file_list_var }}"
        state: absent
      loop: "{{ dest_file_list }}"
      loop_control:
        loop_var: dest_file_list_var
