---
# Tasks file for check_ptf
- name: Init varibles
  ansible.builtin.set_fact:
    check_ptf_ptfs: []
    check_ptf_ptfs_status: {}
    check_ptf_checked_ptf: {}
    check_ptf_ptfs_info: []
    check_ptf_not_loaded_ptfs_list: []
    check_ptf_loaded_ptfs_list: []
    check_ptf_to_be_loadednumber: []
    check_ptf_loaded: []
    check_ptf_compose_list: []
    check_ptf_temporarily_applied_list: []
    check_ptf_temporarily_applied: []

- name: Compose ptf list and ptfs status dict
  ansible.builtin.set_fact:
    check_ptf_ptfs: "{{ check_ptf_ptfs | default([]) + [check_ptf_list_var.ptf_id] }}"
    check_ptf_ptfs_status: "{{ check_ptf_ptfs_status | default({}) | combine({check_ptf_list_var.ptf_id: 'NON-EXISTENT'}) }}"
  loop: '{{ check_ptf_list }}'
  loop_control:
    loop_var: check_ptf_list_var

- name: Print check_ptf_list
  ansible.builtin.debug:
    var: check_ptf_list

- name: Print ptf number list to-be-checked
  ansible.builtin.debug:
    msg: 'ptf numbers to be checked: {{ check_ptf_ptfs }}'

- name: Query the status of the request ptf
  ibm.power_ibmi.ibmi_fix:
    fix_list: '{{ check_ptf_ptfs }}'
    operation: 'query'
  register: check_ptf_check

- name: Compose check result dict
  ansible.builtin.set_fact:
    check_ptf_ptfs_info: "{{ check_ptf_check.ptf_list }}"

# - name: Print check_ptf_ptfs_info
#   ansible.builtin.debug:
#     var: check_ptf_ptfs_info

- name: Compose ptfs status dict
  ansible.builtin.set_fact:
    check_ptf_checked_ptf: "{{ check_ptf_checked_ptf | default({}) | combine({ptfs_info_var.PTF_IDENTIFIER: ptfs_info_var.PTF_LOADED_STATUS}) }}"
  loop: '{{ check_ptf_ptfs_info | list }}'
  loop_control:
    loop_var: ptfs_info_var

# - name: Print check_ptf_checked_ptf
#   ansible.builtin.debug:
#     var: check_ptf_checked_ptf

- name: Combine the query result and unknown ptf
  ansible.builtin.set_fact:
    check_ptf_ptfs_status: "{{ check_ptf_ptfs_status | default({}) | combine(check_ptf_checked_ptf | default({})) }}"

- name: Compose to_be_loadednumber
  ansible.builtin.set_fact:
    check_ptf_to_be_loadednumber: "{{ check_ptf_to_be_loadednumber | default([]) + [ptf_status.key] }}"
  when: ptf_status.value == 'NON-EXISTENT' or ptf_status.value == 'PERMANENTLY REMOVED' or ptf_status.value == 'NOT LOADED'
  with_dict: "{{ check_ptf_ptfs_status }}"
  loop_control:
    loop_var: ptf_status

- name: Compose temporarily_applied
  ansible.builtin.set_fact:
    check_ptf_temporarily_applied: "{{ check_ptf_temporarily_applied | default([]) + [ptf_status.key] }}"
  when: ptf_status.value == 'APPLIED'
  with_dict: "{{ check_ptf_ptfs_status }}"
  loop_control:
    loop_var: ptf_status

- name: Compose loaded
  ansible.builtin.set_fact:
    check_ptf_loaded: "{{ check_ptf_loaded | default([]) + [ptf_status.key] }}"
  when: ptf_status.value == 'LOADED'
  with_dict: "{{ check_ptf_ptfs_status }}"
  loop_control:
    loop_var: ptf_status

# - name: Print check_ptf_loaded
#   ansible.builtin.debug:
#     var: check_ptf_loaded

# - name: Print check_ptf_to_be_loadednumber
#   ansible.builtin.debug:
#     var: check_ptf_to_be_loadednumber

- name: Compose compose_list
  ansible.builtin.set_fact:
    check_ptf_compose_list: []

- name: Compose to_be_loaded
  ansible.builtin.include_tasks: find_ptfinfo.yml
  with_list: "{{ check_ptf_to_be_loadednumber }}"
  loop_control:
    loop_var: ptf_id_var

- name: Set to_be_loaded
  ansible.builtin.set_fact:
    check_ptf_to_be_loaded: "{{ check_ptf_compose_list }}"

#  -name: Print check_ptf_to_be_loaded
#   ansible.builtin.debug:
#     var: check_ptf_to_be_loaded

- name: Call ibm.power_ibmi.ibmi_fix_product_check to filter uninstalled product
  ibm.power_ibmi.ibmi_fix_product_check:
    ptfs: '{{ check_ptf_to_be_loaded }}'
  register: check_ptf_fix_product_check_result
  when: check_ptf_to_be_loaded != [] and check_ptf_check_product

- name: Compose check_ptf_not_loaded_ptfs_list and check_ptf_product_not_installed_ptfs
  ansible.builtin.set_fact:
    check_ptf_not_loaded_ptfs_list: "{{ check_ptf_fix_product_check_result.ptfs_with_product_installed | default([]) }}"
    check_ptf_product_not_installed_ptfs: "{{ check_ptf_fix_product_check_result.ptfs_without_product_installed | default([]) }}"

- name: Compose compose_list
  ansible.builtin.set_fact:
    check_ptf_compose_list: []

- name: Compose check_ptf_loaded_ptfs_list
  ansible.builtin.include_tasks: find_ptfinfo.yml
  with_list: "{{ check_ptf_loaded }}"
  loop_control:
    loop_var: ptf_id_var

- name: Compose check_ptf_loaded_ptfs_list
  ansible.builtin.set_fact:
    check_ptf_loaded_ptfs_list: "{{ check_ptf_compose_list }}"
  when: check_ptf_loaded != []

- name: Compose check_ptf_temporarily_applied_list
  ansible.builtin.include_tasks: find_ptfinfo.yml
  with_list: "{{ check_ptf_temporarily_applied }}"
  loop_control:
    loop_var: ptf_id_var

- name: Compose check_ptf_temporarily_applied_list
  ansible.builtin.set_fact:
    check_ptf_temporarily_applied_list: "{{ check_ptf_compose_list }}"
  when: check_ptf_temporarily_applied != []

- name: Compose check_ptf_ptfs_status
  ansible.builtin.set_fact:
    check_ptf_ptfs_status: "{{ check_ptf_ptfs_status | default({}) | combine({ptf_status.ptf_id: 'PRODUCT_NOT_INSTALLED'}) }}"
  with_list: "{{ check_ptf_product_not_installed_ptfs }}"
  loop_control:
    loop_var: ptf_status
  when: check_ptf_product_not_installed_ptfs != []

- name: Compose check_ptf_ptfs_info
  ansible.builtin.set_fact:
    check_ptf_ptfs_info: "{{ check_ptf_ptfs_info + [{'PTF_IDENTIFIER': ptf_status.key, 'PTF_LOADED_STATUS': ptf_status.value}] }}"
  when: ptf_status.value == 'NON-EXISTENT' or ptf_status.value == 'PRODUCT_NOT_INSTALLED'
  with_dict: "{{ check_ptf_ptfs_status }}"
  loop_control:
    loop_var: ptf_status

- name: Print not loaded ptfs list
  ansible.builtin.debug:
    var: check_ptf_not_loaded_ptfs_list

- name: Print check_ptf_product_not_installed_ptfs
  ansible.builtin.debug:
    var: check_ptf_product_not_installed_ptfs

- name: Print already loaded ptfs list
  ansible.builtin.debug:
    var: check_ptf_loaded_ptfs_list

- name: Print Temporarily applied ptfs list
  ansible.builtin.debug:
    var: check_ptf_temporarily_applied_list

- name: Print check_ptf_ptfs status
  ansible.builtin.debug:
    var: check_ptf_ptfs_status

- name: Print check_ptf_ptfs info
  ansible.builtin.debug:
    var: check_ptf_ptfs_info
