# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- name: Playbook for checking products
  hosts: all
  gather_facts: false

  vars:
    become_user_name: null
    become_user_password: null

  tasks:
    - name: Return information about all licensed products and features that will expire within the next 2 weeks.
      ibm.power_ibmi.ibmi_sql_query:
        sql: "SELECT *
                  FROM QSYS2.LICENSE_INFO
                  WHERE LICENSE_EXPIRATION <= CURRENT DATE + 50 DAYS"
        become_user: '{{ become_user_name }}'
        become_user_password: '{{ become_user_password }}'
        expected_row_count: 0
      register: expire_within_next_2_weeks
      tags: expire_within_next_2_weeks
      failed_when: false

    - name: Return information about all licensed products and features that will expire within the next 2 weeks
            for installed products only
      ibm.power_ibmi.ibmi_sql_query:
        sql: "SELECT *
                  FROM QSYS2.LICENSE_INFO
                  WHERE INSTALLED = 'YES'
                        AND LICENSE_EXPIRATION <= CURRENT DATE + 50 DAYS"
        become_user: '{{ become_user_name }}'
        become_user_password: '{{ become_user_password }}'
        expected_row_count: 0
      register: expire_within_next_2_weeks
      tags:
        - expire_within_next_2_weeks
      failed_when: false
