- name: Generate a ramdom number
  ansible.builtin.set_fact:
    random_postfix: '{{ 9999999 | random }}'

- name: Compose image name
  ansible.builtin.set_fact:
    image_name_to_be_created: '{{ image_name }}_{{ random_postfix }}'

- name: Create VM snapshot
  ansible.builtin.shell: . /opt/ibm/powervc/powervcrc  && nova --os-username={{ ansible_ssh_user }} --os-password={{ ansible_ssh_pass }}
            --os-project-name={{ project }}  --os-project-domain-name={{ project_domain }} --os-user-domain-name={{ user_domain }}
            image-create {{ vm_name }} {{ image_name_to_be_created }}
  register: image_create_result
  no_log: true
  changed_when: image_create_result.rc == 0

- name: Gather information about a previously created image named {{ image_name_to_be_created }}
  openstack.cloud.image_info:
    auth:
      auth_url: https://{{ ansible_ssh_host }}:5000/v3
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
      project_name: '{{ project }}'
      project_domain_name: '{{ project_domain }}'
      user_domain_name: '{{ user_domain }}'
    image: '{{ image_name_to_be_created }}'
    verify: '{{ verify_cert }}'
  register: image_info

- name: Compose openstack_image
  ansible.builtin.set_fact:
    openstack_image: '{{ image_info }}'

- name: Display openstack_image
  ansible.builtin.debug:
    var: openstack_image
