# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# Description:
  # The playbook file is to provide an example about how to configure passwordless ssh login.

# Parameters:
  # key_path      -- Specifies the path of the private rsa key, if the key doesn't the playbook creates one.
  # source_system -- Specifies the system whose public key is added to authorized_keys of target_system. After that whose user which is authorized
  #                  by target_system can log in target_system via ssh without providing password.
  # target_system -- Specifies the system which performs as a server in futher ssh connection.

# Command example:
  # ansible-playbook ./configure_passwordless_ssh_login.yml -e  "{'source_system': 'reposerver', 'target_system': 'ibmi'}"
---
- name: Playbook to configure passwordless ssh login from source_system to target_system
  hosts: '{{ target_system | default([]) }}'
  strategy: linear
  gather_facts: false

  vars:
    key_path: '~/.ssh/id_rsa'
    source_system: ''

  tasks:
    - name: Check key pair state    # noqa: run-once[task]
      ansible.builtin.stat:
        path: '{{ key_path }}'
      register: key_state
      run_once: true
      delegate_to: '{{ source_system }}'

    - name: Generate a key if the key doesn't exist    # noqa: run-once[task]
      when: not key_state.stat.exists
      run_once: true
      delegate_to: '{{ source_system }}'
      block:
        - name: Present the home directory
          ansible.builtin.file:
            state: directory
            path: ~/.ssh
            mode: '0700'

        - name: Generate a key pair
          ansible.builtin.command: ssh-keygen -q -t rsa -f {{ key_path }} -C "" -N "" -m PEM
          args:
            creates: '{{ key_path }}'

    - name: Obtain public key
      ansible.builtin.command: cat  {{ key_path }}.pub
      register: cat_result
      delegate_to: '{{ source_system }}'
      changed_when: false

    - name: Copy public key to fact
      ansible.builtin.set_fact:
        public_key_content: "{{ cat_result.stdout }}"

    - name: Add public key to remote IBM i endpoints
      ansible.builtin.include_role:
        name: configure_passwordless_ssh_login
      vars:
        configure_passwordless_ssh_login_target_user: '{{ ansible_ssh_user }}'
        configure_passwordless_ssh_login_public_key: '{{ public_key_content }}'
