# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# Description:
  # This playbook is used for 1st level solution. It will get the individual ptfs' information in catalog. Then call check_ptf role
  # to check which ptfs are not already applied or loaded on the target syste. Then call sync_apply_individual_ptfs_lv1 role to transfer
  # the unloaded or unapplied ptfs to the target system. Then load and apply.

# Parameters:
  # repo_server -- The IBM i/Linux server stores PTFs and PTF groups. 
  # target_system -- The target IBM i server that receives and applies the PTFs.
  # ptfs_list -- Specifies the PTFs' list.
  # delete -- Specifies whether or not to delete the file install dir on target server after apply. The default value is true.
  # image_root -- Specifies the image files' dir on the repo_server. This should be the root dir of all the image files.
  # apply_all_loaded_ptfs -- Controls whether all loaded ptf will be applied. The default value is true.
  # temp_or_perm -- Controls whether the target PTFs will be permanent applied or temporary applied. Value can be  '*TEMP' or '*PERM'. Default value is '*TEMP'.
  # delayed_option -- Controls whether the PTF is delayed apply or not. Value can be '*YES', '*NO' or '*IMMDLY'. Default value is '*IMMDLY'. 
  # auto_ipl -- Controls whether an immediate reboot will be launched automatically if at least one ptf requests an IPL for permanent applied or temporary applied. The default value is false.

# Output:
  # all_ptf_status -- All input ptf's status
  # apply_fail_list -- Apply failed ptf list
  # apply_success_list -- Apply successful ptf list
  # not_in_catalog -- The list of ptfs which information is not in the catalog

# Command example: 
  # ansible-playbook ./sync_apply_individual_ptfs_lv1.yml -e "{'target_system': 'systemA', 'repo_server': 'systemB', 'image_root': '/home/test/PTF', 'ptfs_list': ['SI67856', 'SI69375', 'SI73751'], 'apply_all_loaded_ptfs': true, 'temp_or_perm': '*TEMP', 'delayed_option': '*IMMDLY', 'auto_ipl': false, 'delete': true}"
---
- name: Sync and apply a list of individual ptfs
  hosts: '{{ target_system }}'
  gather_facts: false
  collections:
    - ibm.power_ibmi

  vars:
    repo_server: "{{ repo_server }}"

  tasks:
    - name: init varibles
      set_fact:
        check_ptf_list: []

    - name: Compose ptf id list
      set_fact:
        ptf_id_list: "{{ ptf_id_list | default([]) + [{'ptf_id': ptfs_list_var}] }}"
      loop: "{{ ptfs_list }}"
      loop_control:
        loop_var: ptfs_list_var

    - name: Refresh PTF DB information in catalog
      ibmi_fix_repo_lv1:
        image_root: "{{ image_root }}"
        action: "refresh"
      delegate_to: "{{ repo_server }}"
      register: fix_repo_refresh_result

    - name: Print the PTF group refresh result
      debug:
        var: fix_repo_refresh_result

    - name: Include fix_repo_lv1_find_individual_ptf role to recursively find individual ptfs in catalog
      include_role:
        name: fix_repo_lv1_find_individual_ptf
      vars:
        ptfs_list: "{{ ptfs_list }}"
        src_host: "{{ repo_server }}"
        image_root: "{{ image_root }}"

    - name: fail condition
      fail:
        msg: "No available individual ptf in catalog, quit."
      when: ptf_find_result == []

    - name: Call compose_check_ptf_list.yml to compose check_ptf_list
      include_tasks: compose_check_ptf_list.yml
      loop: "{{ ptf_find_result }}"
      loop_control:
        loop_var: ptf_find_result_var

    - name: Print check_ptf_list
      debug:
        var: check_ptf_list

    - name: Include check_ptf role to determine which ptfs need to apply
      include_role:
        name: check_ptf

    - block:
        - name: No individual ptf need to be applied msg
          debug:
            msg: "No individual ptf need to be applied, quit."

        - name: end_host
          meta: end_host
      when: not_loaded_ptfs_list == [] and loaded_ptfs_list == []

    - name: Include sync_apply_individual_ptfs_lv1 role to transfer a list of individual ptfs to target ibm i, then load and apply
      include_role:
        name: sync_apply_individual_ptfs_lv1
      vars:
        not_loaded_list: "{{ not_loaded_ptfs_list }}"
        src_host: "{{ repo_server }}"
        already_loaded_list: "{{ loaded_ptfs_list }}"

    - name: Include check_ptf role again to get the final applied result
      include_role:
        name: check_ptf
      vars:
        check_ptf_list: "{{ ptf_id_list }}"
        check_product: false

    - name: Compose final result
      set_fact:
        final_result: "{{ {'not_in_catalog': ptf_fail_list, 'apply_success_list': apply_success_list, 'apply_fail_list': apply_fail_list, \
        'all_ptf_status': ptfs_status} }}"

    - name: Print final ptfs status
      debug:
        var: final_result
