---
- name: Transfer a PTF group files from repo server to target system, and apply
# This playbook will get the PTF group information in catalog. Then call sync_apply_ptf_group role to transfer the PTF group files
# to the target system. Then apply.

# Command example: ansible-playbook ./sync_apply_ptf_group.yml -e \
# "{'target_system': 'systemA', 'repo_server': 'reposerver', \
# 'ptf_group': {'ptf_group_number':'SF99740', 'ptf_group_level':'20121'}}"
  hosts: '{{ target_system }}'
  gather_facts: false
  collections:
    - ibm.power_ibmi

  vars:
    repo_server: "{{ repo_server }}"
    ptf_group: "{{ ptf_group }}"

  tasks:
    - name: Get the PTF group information in catalog
      ibmi_fix_repo:
        type: "ptf_group"
        checksum: true
        action: "find"
        parameters: |
          - "{{ {'ptf_group_number': ptf_group.ptf_group_number, \
             'ptf_group_level': ptf_group.ptf_group_level | default(omit), \
             'release_date': ptf_group.release_date | default(omit), 'additional_param':'ORDER BY release_date DESC LIMIT 1'} }}"
      delegate_to: "{{ repo_server }}"
      register: fix_repo_find_result

    - name: Print the PTF group information
      debug:
        var: fix_repo_find_result

    - block:
        - name: Debug msg
          debug:
            msg: "PTF group information is not in catalog, quit."
        - name: end_host
          meta: end_host
      when: fix_repo_find_result.success_list is not defined or fix_repo_find_result.success_list == []

    - name: Get the PTF group information in download_status table, in case the order is still dwonloading
      ibmi_fix_repo:
        type: "download_status"
        action: "find"
        parameters: |
          - "{{ {'ptf_group_number': ptf_group.ptf_group_number, \
             'ptf_group_level': ptf_group.ptf_group_level | default(omit), \
             'release_date': ptf_group.release_date | default(omit), \
             'additional_param':'ORDER BY release_date DESC LIMIT 1'} }}"
      delegate_to: "{{ repo_server }}"
      register: download_status_find_result

    - name: Print the download_status table information
      debug:
        var: download_status_find_result

    - block:
        - name: Debug msg
          debug:
            msg: "The newest PTF group is still downloading, quit."
        - name: end_host
          meta: end_host
      when: download_status_find_result.success_list[0].download_status == 'downloading'

    - name: Compose apply list
      set_fact:
        ptf_group_information: "{{ fix_repo_find_result.success_list[0] }}"

    - name: Include sync_apply_ptf_group role to transfer PTF group files to target ibm i, and apply
      include_role:
        name: sync_apply_ptf_group
      vars:
        ptf_group_info: "{{ ptf_group_information }}"
        src_host: "{{ repo_server }}"
