- name: Playbook to start build
  hosts: localhost
  tasks:
    - name: Set build_number
      ansible.builtin.set_fact:
        build_number: "{{ 9999 | random }}"

    - name: Define build stats
      ansible.builtin.set_stats:
        data:
          build_lib: "BUILD_{{ build_number }}"
          build_path: "/tmp/BUILD_{{ build_number }}"

    - name: Define VM info stats
      ansible.builtin.set_stats:
        data:
          vm_name: "VM-BUILD_{{ build_number }}"
      when: provision|bool

    - name: Display build information
      ansible.builtin.debug:
        msg: "Build number {{ build_number }} starts!"
