- name: Playbook for post build actions
  hosts: localhost
  tasks:
    - name: Add VM to ansible in-memory inventory (vm-{{ build_lib }})
      ansible.builtin.add_host:
        name: build_system
        ansible_ssh_host: '{{ build_system_ip }}'
        ansible_user: '{{ build_system_user }}'
        ansible_ssh_pass: '{{ build_system_pass }}'
        groups: build_systems
        ansible_ssh_extra_args: -o StrictHostKeyChecking=no
        ansible_python_interpreter: /QOpensys/pkgs/bin/python3
      when: provision | bool

    - name: Run PGM built with STMFs
      ibm.power_ibmi.ibmi_cl_command:
        cmd: CALL {{ build_lib }}/SENDMSG
      register: callpgm
      when: build_with_stmfs|bool
      delegate_to: '{{ item }}'
      with_items:
        - "{{ host_names.split() }}"

    - name: Run PGM built from PF members
      ibm.power_ibmi.ibmi_cl_command:
        cmd: CALL {{ build_lib }}/SAMPLECL
      register: callpgm
      when: not build_with_stmfs|bool
      delegate_to: '{{ item }}'
      with_items:
        - "{{ host_names.split() }}"
