# New vm info from OpenStack
- name: Playbook for provisioning VM
  hosts: localhost
  tasks:
    - name: Block for when provision
      when: provision|bool
      block:
        - name: Step 1.1 - Add PowerVC host to Ansible in-memory inventory ({{ powervc_host }})
          ansible.builtin.add_host:
            name: 'powervc'
            ansible_user: '{{ powervc_admin }}'
            ansible_ssh_pass: '{{ powervc_admin_password }}'
            ansible_ssh_extra_args: -o StrictHostKeyChecking=no
            ansible_python_interpreter: /usr/bin/python3
            ansible_ssh_host: '{{ powervc_host }}'
          no_log: true

        - name: Deploy a new VM
          openstack.cloud.server:
            auth:
              auth_url: https://{{ powervc_host }}:5000/v3
              username: '{{ powervc_admin }}'
              password: '{{ powervc_admin_password }}'
              project_name: '{{ powervc_project }}'
              project_domain_name: '{{ project_domain }}'
              user_domain_name: '{{ user_domain }}'
            name: '{{ vm_name }}'
            image: '{{ image_name_or_id }}'
            flavor: '{{ flavor_name_or_id }}'
            verify: '{{ verify_cert | bool}}'
            network: '{{ network }}'
            timeout: '{{ deploy_timeout }}'
            userdata: '{{ deploy_userdata }}'
          register: vm_info
          delegate_to: 'powervc'

        - name: Set build_system_ip for following job use
          ansible.builtin.set_stats:
            data:
              build_system_ip: "{{ vm_info.server.accessIPv4 }}"
