# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0

# setup ibmi off line
---
- name: Check whether python has been installed. If not, install it in following tasks.
  ansible.builtin.raw: ls -l /QOpensys/pkgs/bin/{{ python_interpreter_version }}
  args:
    executable: /qopensys/usr/bin/qsh
  register: default_python_existance
  ignore_errors: true
  changed_when: false

- name: Install python
  when: default_python_existance.rc != 0
  block:
    - name: Fail if package path not provided
      ansible.builtin.fail:
        msg: "package_path is not provided, please provide the directory path where the installation packages locate at"
      when: package_path == ""

    - name: Find out the name of python3 installation package
      ansible.builtin.shell: ls {{ package_path }}/*.rpm
      delegate_to: localhost
      register: python_file_list
      changed_when: false

    - name: Set up rpm list
      ansible.builtin.set_fact:
        rpm_list: "{{  rpm_list|default([]) + [rpm_full_path.split('/')[-1]]  }}"
      loop: "{{ python_file_list.stdout_lines }}"
      loop_control:
        loop_var: rpm_full_path

    - name: Transfer files
      ansible.builtin.include_tasks: transfer_files.yml
      loop: "{{ rpm_list }}"
      loop_control:
        loop_var: package
      vars:
        target_path: "{{ remote_temp_dir }}"

    - name: Find out the name of python3 installation package
      ansible.builtin.raw: ls -l {{ remote_temp_dir }}/*.rpm
      changed_when: false

    - name: Install the package
      # raw: "/QOpensys/pkgs/bin/yum --disablerepo=ibm install {{ remote_temp_dir }}/*.rpm -y"
      ansible.builtin.raw: "/QOpensys/pkgs/bin/yum install {{ remote_temp_dir }}/*.rpm -y"
      changed_when: true

- name: Install dependencies
  when: default_python_existance.rc == 0
  block:
    - name: Set not having rpm
      ansible.builtin.set_fact:
        has_rpm_to_be_installed: false

    - name: Include install dependencies
      ansible.builtin.include_tasks: ibmi_install_dependencies.yml
      vars:
        python: "{{ python_version }}"
      loop: "{{ required_rpms }}"
      loop_control:
        loop_var: dependency

    - name: Install the package
      # raw: "/QOpensys/pkgs/bin/yum --disablerepo=ibm install {{ remote_temp_dir }}/*.rpm -y"
      ansible.builtin.raw: "/QOpensys/pkgs/bin/yum install {{ remote_temp_dir }}/*.rpm -y"
      changed_when: has_rpm_to_be_installed
      when: has_rpm_to_be_installed
