# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0

# setup ibmi off line
---
- name: Check whether the installation package can be found on ansible server. Package {{ package }}
  ansible.builtin.stat:
    path: "{{ package_path }}/{{ package }}"
  delegate_to: localhost
  register: installation_file_state

- name: Set transfer cmd
  ansible.builtin.set_fact:
    transfer_command: "scp {{ package_path }}/{{ package }} {{ ibmi_user }}@{{ ibmi_host }}:{{ target_path }}/"

- name: Transfer installation package to remote IBM i and the target directory is {{ target_path }}
  no_log: true
  ansible.builtin.shell: 'sshpass -p "{{ ibmi_pass }}" {{ transfer_command }}'    # noqa: command-instead-of-shell
  delegate_to: localhost
  when: ibmi_pass != ""
  changed_when: ibmi_pass != ""

- name: Transfer installation package to remote IBM i and the target directory is {{ target_path }}
  ansible.builtin.shell: "{{ transfer_command }}"    # noqa: command-instead-of-shell
  delegate_to: localhost
  when: ibmi_pass == ""
  changed_when: ibmi_pass == ""
