# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- name: Set package_name host fact
  ansible.builtin.set_fact:
    package_name: "{{ python }}-{{ item }}"

- name: Verify package installed. {{ item }}
  ansible.builtin.raw: /QOpensys/pkgs/bin/yum list installed | grep {{ package_name }}
  register: package_query_result
  ignore_errors: true
  changed_when: false

- name: Install package if it is not installed. {{ item }}
  ansible.builtin.raw: /QOpensys/pkgs/bin/yum install {{ python }}-{{ item }} -y
  # when: '"{{ python }}-{{ item }}" not in package_query_result.stdout'
  when: package_name not in package_query_result.stdout
  changed_when: package_name not in package_query_result.stdout
