- name: Remove, if exists, {{ local_workspace }}
  ansible.builtin.file:
    path: '{{ local_workspace }}'
    state: 'absent'

- name: Create {{ local_workspace }}
  ansible.builtin.file:
    path: '{{ local_workspace }}'
    state: 'directory'
    mode: '0755'

- name: Git clone from source repository
  ansible.builtin.git:
    repo: '{{ git_repo_url }}'
    dest: '{{ local_workspace }}'
    version: '{{ git_branch }}'
    key_file: ~/.ssh/id_rsa
