---
# Role for load_apply_ptfs
- name: Include load_ptf role to load PTFs
  ansible.builtin.include_role:
    name: load_ptf
  vars:
    to_be_loaded_list: "{{ to_be_loaded_ptf_list }}"
  when: to_be_loaded_ptf_list | default([]) != []

- name: Include apply_ptf role to apply PTFs
  ansible.builtin.include_role:
    name: apply_ptf
  vars:
    to_be_applied_list: "{{ load_success_list | default([]) + loaded_list }}"
  when: load_success_list | default([]) + loaded_list != []
