#ibmi-sql-sample.yml 
#The sample file is to provide an example about how to create a table, insert a row, query the table and drop the table
---
- hosts: ibmi
  gather_facts: no
  collections:
   - ibm.power_ibmi
  
  tasks:
    - block:

      - name: Ocupacion de disco
        ibmi_sql_query:
          sql: "select ASP_NUMBER, TOTAL_CAPACITY_AVAILABLE, TOTAL_CAPACITY, DEC(DEC(TOTAL_CAPACITY_AVAILABLE, 19, 2)/ DEC(TOTAL_CAPACITY, 19, 2) * 100, 19, 2) AS AVAILABLE_SPACE from qsys2.asp_info"
        register: sql_query_result
      - debug:
          var: sql_query_result.row

      - name: PTF level
        ibmi_sql_query:
          sql: "select PTF_GROUP_NAME, PTF_GROUP_LEVEL, PTF_GROUP_STATUS from qsys2.GROUP_PTF_INFO"

        register: sql_query_result1
      - debug:
          var: sql_query_result1.row

      
      
