#ibmi-sql-sample.yml 
#The sample file is to provide an example about how to create a table, insert a row, query the table and drop the table
---
- hosts: ibmi
  gather_facts: no
  collections:
   - ibm.power_ibmi
  
  tasks:
    - block:


      - name: Ocupacion de disco
        ibmi_sql_query:
          sql: "select ASP_NUMBER, DEVD_NAME, DISK_UNITS, PRESENT,  TOTAL_CAPACITY_AVAILABLE, TOTAL_CAPACITY, DEC(DEC(TOTAL_CAPACITY_AVAILABLE, 19, 2) DEC(TOTAL_CAPACITY, 19, 2) * 100, 19, 2) AS AVAILABLE_SPACE from qsys2.asp_info ORDER BY 7 ASC"
        register: sql_query_result
      - debug:
          var: sql_query_result.row

      - name: Ocupacion de disco
        ibmi_sql_query:
          sql: "With iLevel(iVersion, iRelease) AS
(
select OS_VERSION, OS_RELEASE from sysibmadm.env_sys_info
)
SELECT VARCHAR(GRP_CRNCY,26) AS "GRPCUR",
       GRP_ID,  VARCHAR(GRP_TITLE, 20) AS "NAME",
       GRP_LVL, GRP_IBMLVL, GRP_LSTUPD,
       GRP_RLS, GRP_SYSSTS
FROM iLevel, systools.group_ptf_currency P
WHERE ptf_group_release =
'R' CONCAT iVersion CONCAT iRelease concat '0'
ORDER BY ptf_group_level_available -
ptf_group_level_installed DESC"

        register: sql_query_result1
      - debug:
          var: sql_query_result1.row

      
      
