- name: Block for when pre_cleanup
  when: pre_cleanup|bool
  block:
    - name: Check inventory
      ansible.builtin.uri:
        url: "{{ tower_api_url }}/inventories/?name={{ inventory_name }}"
        headers:
          Authorization: Bearer {{ token }}
        validate_certs: false
      register: check_inventory

    - name: Block for when check_inventory.json.count == 1
      when: check_inventory.json.count == 1
      block:
        - name: Delete the inventory
          ansible.builtin.uri:
            url: "{{ tower_api_url }}/inventories/{{ check_inventory.json.results[0].id }}/"
            status_code: 204, 202
            method: DELETE
            headers:
              Authorization: Bearer {{ token }}
            validate_certs: false
          register: delete_inventory

        - name: Check inventory again
          ansible.builtin.uri:
            url: "{{ tower_api_url }}/inventories/?name={{ inventory_name }}"
            headers:
              Authorization: Bearer {{ token }}
            validate_certs: false
          register: check_inventory_again
          until: check_inventory_again.json.count == 0
          retries: 3
          delay: 10

- name: Create an Inventory
  ansible.builtin.uri:
    url: "{{ tower_api_url }}/inventories/"
    status_code: 201
    method: POST
    headers:
      Authorization: Bearer {{ token }}
    body_format: json
    body:
      organization: 1
      name: "{{ inventory_name }}"
    validate_certs: false
  register: inventory
  failed_when: inventory.json.id | int < 0
