- name: Block for when pre_cleanup
  when: pre_cleanup|bool
  block:
    - name: Check Machine Credential
      ansible.builtin.uri:
        url: "{{ tower_api_url }}/credentials/?name={{ credential_name }}"
        headers:
          Authorization: Bearer {{ token }}
        validate_certs: false
      register: check_machine_cred

    - name: Block for when check_machine_cred.json.count == 1
      when: check_machine_cred.json.count == 1
      block:
        - name: Delete The Machine Credential
          ansible.builtin.uri:
            url: "{{ tower_api_url }}/credentials/{{ check_machine_cred.json.results[0].id }}/"
            status_code: 204
            method: DELETE
            headers:
              Authorization: Bearer {{ token }}
            validate_certs: false
          register: delete_machine_cred

- name: Add Credentials to The Job Template
  no_log: true
  ansible.builtin.uri:
    url: "{{ tower_api_url }}/credentials/"
    status_code: 201
    method: POST
    headers:
      Authorization: Bearer {{ token }}
    body_format: json
    body:
      credential_type: 1
      name: "{{ credential_name }}"
      user: 1
      inputs:
        password: "{{ build_system_pass }}"
        username: "{{ build_system_user }}"
    validate_certs: false
  register: host_credentials
  failed_when: host_credentials.json.id | int < 0

- name: Set job_credential_body
  ansible.builtin.set_fact:
    job_credential_body: '{ "id": {{ host_credentials.json.id | int }} }'
