- name: Revoke the used ansible tower token
  ansible.builtin.uri:
    url: "{{ tower_api_url }}/tokens/{{ token_id }}/"
    status_code: 204
    method: DELETE
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: false
