- name: Get a token
  no_log: true
  ansible.builtin.uri:
    url: "{{ tower_api_url }}/users/1/personal_tokens/"
    method: POST
    status_code: [201]
    body_format: json
    user: "{{ tower_username }}"
    password: "{{ tower_password }}"
    force_basic_auth: true
    body:
      description: Personal Tower CLI token
      application: null
      scope: write
    validate_certs: false
    return_content: true
  register: tower_token

- name: Set token info
  ansible.builtin.set_fact:
    token: "{{ tower_token.json.token }}"
    token_id: "{{ tower_token.json.id }}"
