# Copyright (c) IBM Corporation 2019, 2021
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

---
- name: Prompt input parameters, press Enter to accept default values.
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: prefix
      prompt: Enter your naming prefix for this project
      default: "sample"
      private: false

    - name: pre_cleanup
      prompt: Whether to clean up before running (Yes/No)
      default: "Yes"
      private: false

    - name: tower_url
      prompt: Enter your Ansible Tower's URL
      default: "https://<your-ansible-tower-url>"
      private: false

    - name: tower_username
      prompt: Enter your Ansible Tower's user name
      default: "admin"
      private: false

    - name: tower_password
      prompt: Enter your Ansible Tower's password
      private: true
      confirm: true
      default: ""

    - name: git_url
      prompt: Enter your SCM repository's URL
      default: "https://github.com/IBM/ansible-for-i-usecases.git"
      private: false

    - name: playbook_names
      prompt: Enter your playbooks' names in order (use space as separator)
      default: >
        usecases/cicd-tower/build_start.yml
        usecases/cicd-tower/provision_vm.yml
        usecases/cicd-tower/add_build_system.yml
        usecases/cicd-tower/build.yml
        usecases/cicd-tower/post_build_actions.yml
        usecases/cicd-tower/cleanup.yml
      private: false

    - name: git_repo_url
      prompt: Enter the source code repository's URL for your project
      default: "https://github.com/IBM/cicd-source.git"
      private: false

    - name: git_branch
      prompt: Enter the branch of the source code repository for your project
      default: "master"
      private: false

    - name: github_user_name
      prompt: Enter your github user name
      default: ""
      private: false

    - name: github_access_token
      prompt: Enter the personal access token generated from github, not neccessary when accessing public repositories.
      private: true
      default: ""

    - name: build_with_stmfs
      prompt: Are you building your app with STMFs or PF members? Yes for SMTFs, No for PF members. (Yes/No)
      default: "Yes"
      private: false

    - name: cleanup
      prompt: Do you want to do clean up after each build? (Yes/No)
      default: "Yes"
      private: false

    - name: provision
      prompt: Do you want to provision a new VM for building? (Yes/No)
      default: "Yes"
      private: false

    - name: build_system_user
      prompt: Enter your IBM i build machine user name
      default: ""
      private: false

    - name: build_system_pass
      prompt: Enter your IBM i build machine user password
      private: true
      confirm: true
      default: ""

  vars:
    tower_api_url: "{{ tower_url | regex_replace('\\/$', '') }}/api/v2"
    playbooks: "{{ playbook_names.split() }}"

  tasks:
    - name: Initialize facts
      ansible.builtin.set_fact:
        credential_name: "{{ prefix }}_machine_cred"
        inventory_name: "{{ prefix }}_systems"
        project_name: "{{ prefix }}_project"
        template_name: "{{ prefix }}_template"
        workflow_name: "{{ prefix }}_workflow"
        github_token_name: "{{ prefix }}_github_token"
        get_result_retry: 300
        get_result_retry_delay: 10

    - name: Block for when not provision
      when: not provision|bool
      block:
        - name: Pause for host_name
          ansible.builtin.pause:
            prompt: |
              You didn't choose to provision a new VM for building,
              please enter your build machine IP address here (use space as separator for multiple hosts)
          register: host_name

    - name: Block for when provision
      when: provision|bool
      block:
        - name: Pause for powervc_host
          ansible.builtin.pause:
            prompt: "Enter powervc host for provisioning"
          register: powervc_host

        - name: Pause for powervc_admin
          ansible.builtin.pause:
            prompt: "Enter powervc admin for provisioning"
          register: powervc_admin

        - name: Pause for powervc_admin_password
          ansible.builtin.pause:
            prompt: "Enter powervc admin password for provisioning"
            echo: false
          register: powervc_admin_password

        - name: Pause for powervc_project
          ansible.builtin.pause:
            prompt: "Enter the project name in powervc host for provisioning"
          register: powervc_project

        - name: Pause for project_domain
          ansible.builtin.pause:
            prompt: "Enter the project domain name in powervc host for provisioning"
          register: project_domain

        - name: Pause for user_domain
          ansible.builtin.pause:
            prompt: "Enter the user_domain in powervc host for provisioning"
          register: user_domain

        - name: Pause for verify_cert
          ansible.builtin.pause:
            prompt: "Do you want to verify cert in provisioning? (Yes/No)"
          register: verify_cert

        - name: Pause for network
          ansible.builtin.pause:
            prompt: "Enter the Name or ID of a network to attach this instance to"
          register: network

        - name: Pause for image_name_or_id
          ansible.builtin.pause:
            prompt: "Enter the image name or id in powervc host for provisioning"
          register: image_name_or_id

        - name: Pause for flavor_name_or_id
          ansible.builtin.pause:
            prompt: "Enter the flavor name or id in powervc host for provisioning"
          register: flavor_name_or_id

        - name: Pause for deploy_timeout
          ansible.builtin.pause:
            prompt: "Enter the timeout(seconds) value of provisioning VM in powervc host"
          register: deploy_timeout

        - name: Set facts
          ansible.builtin.set_fact:
            network: '{{ network.user_input }}'
            deploy_userdata_value: |
              {%- raw -%}#!/bin/sh
              mkdir /home/{{ build_system_user }}
              system "CRTUSRPRF USRPRF({{ build_system_user }}) PASSWORD({{ build_system_pass }}) USRCLS(*SECOFR) HOMEDIR('/home/{{ build_system_user }}')"
              system "chgtcpsvr svrspcval(*sshd) autostart(*yes)"
              system "strtcpsvr *sshd"
              {% endraw %}

    - name: Block for steps
      block:
        - name: Step 1 - login and get a Token
          ansible.builtin.include_tasks: login.yml

        - name: Step 2 - add a new inventory
          ansible.builtin.include_tasks: add_inventory.yml

        - name: Block for when not provision
          when: not provision|bool
          block:
            - name: Step 3 - add new hosts
              ansible.builtin.include_tasks: add_hosts.yml

            - name: Step 4 - add a host access token
              ansible.builtin.include_tasks: add_credential.yml

        - name: Block for when github_access_token != ""
          when: github_access_token != ""
          block:
            - name: Step 5 - add a github access token
              ansible.builtin.include_tasks: add_github_token.yml

        - name: Step 6 - add a new project
          ansible.builtin.include_tasks: add_project.yml

        - name: Step 7 - add a workflow template
          ansible.builtin.include_tasks: add_workflow.yml

        - name: Step 8 - add job templates to the workflow
          ansible.builtin.include_tasks: add_job.yml
          loop: "{{ playbooks }}"
          loop_control:
            loop_var: playbook

        - name: Step 9 - run the workflow
          ansible.builtin.include_tasks: run_workflow.yml

        - name: Step 10 - show the result
          ansible.builtin.include_tasks: show_result.yml

        - name: Step 11 - clean up used tokens
          ansible.builtin.include_tasks: cleanup.yml
