- name: Check A Workflow To Run
  ansible.builtin.uri:
    url: "{{ tower_api_url }}/workflow_job_templates/{{ workflow_job_templates.json.id }}/launch/"
    status_code: 200
    method: GET
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: false
  register: workflow_job_templates_status
  when: workflow_job_templates.json.id | int >= 0

- name: Launch A Workflow
  ansible.builtin.uri:
    url: "{{ tower_api_url }}/workflow_job_templates/{{ workflow_job_templates.json.id }}/launch/"
    status_code: 201
    method: POST
    headers:
      Authorization: Bearer {{ token }}
    validate_certs: false
  register: workflow_job
  when: workflow_job_templates.json.id | int >= 0 and
      not workflow_job_templates.json.ask_inventory_on_launch and
      not workflow_job_templates.json.ask_scm_branch_on_launch

- name: Display The Workflow's URL
  ansible.builtin.debug:
    msg: "Workflow URL: {{ tower_url | regex_replace('\\/$', '') }}/#/workflows/{{ workflow_job.json.id }}"

- name: Display The Workflow's API URL
  ansible.builtin.debug:
    msg: "Workflow API URL: {{ tower_api_url }}/workflow_jobs/{{ workflow_job.json.id }}"
