---
# Task for apply.yml
- name: Initialize
  ansible.builtin.set_fact:
    path: "~/PTF/singleptf/{{ not_loaded_list_var.file_path | basename }}"

- name: Compose path
  ansible.builtin.set_fact:
    path: "{{ path | regex_replace('~', home_dir.stdout) }}"
  when: path | regex_search("^~")

- name: Debug path
  ansible.builtin.debug:
    var: path

- name: Apply PTF
  block:
    - name: Apply PTF using bin file
      ibm.power_ibmi.ibmi_fix_imgclg:
        src: '{{ path }}'
        apply_type: "*IMMDLY"
        rollback: true
      register: apply_result
      ignore_errors: true

    - name: Print apply result
      ansible.builtin.debug:
        var: apply_result

    - name: Apply failure handling
      when: apply_result.rc != 0
      block:
        - name: Print apply fail result
          ansible.builtin.debug:
            msg: "PTF {{ not_loaded_list_var.ptf_id }} applied fail. Please see above job log"

        - name: Compose apply fail list
          ansible.builtin.set_fact:
            apply_fail_list: "{{ apply_fail_list | default([]) + [not_loaded_list_var.ptf_id] }}"

    - name: Apply success
      when: apply_result.rc == 0
      block:
        - name: Print apply success result
          ansible.builtin.debug:
            msg: "PTF {{ not_loaded_list_var.ptf_id }} applied succesfully"

        - name: Debug not_loaded_list_var.ptf_id
          ansible.builtin.debug:
            var: not_loaded_list_var.ptf_id

        - name: Compose apply success list
          ansible.builtin.set_fact:
            apply_success_list: "{{ apply_success_list | default([]) + [not_loaded_list_var.ptf_id] }}"
