galaxy_info:
  author: Zhu Lijun
  description: Ansible role for applying all loaded ptfs
  company: IBM
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: GenericUNIX    # IBM i PASE
      versions:
        - "all"

  galaxy_tags: []
dependencies: []
