# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# ibmi-fix-repo-single-ptf.yml
# Provide an example on how to manipulate the PTF database with individual fixes
---
- name: Playbook to manipulate repo using individual PTFs
  hosts: all
  gather_facts: false

  tasks:
    - name: Tasks performing operations with single PTF records
      block:
        - name: Task add_single_ptf_records
          ibm.power_ibmi.ibmi_fix_repo:
            action: "add"
            type: "single_ptf"
            checksum: true
            parameters:
              - {
                "ptf_id": "SI67955",
                "file_path": "/QSYS.LIB/QGPL.LIB/QSI67955.FILE",
                "product": "5770SS1",
              }
              - {
                "ptf_id": "MF65472",
                "file_path": "/QSYS.LIB/QGPL.LIB/QMF65472.FILE",
                "product": "5770SS1",
              }
              - {
                "ptf_id": "SI71806",
                "file_path": "/QSYS.LIB/QGPL.LIB/QSI71806.FILE",
                "product": "5733OPS",
              }
              - {
                "ptf_id": "SI00000",
                "file_path": "/QSYS.LIB/QGPL.LIB/QSI00000.FILE",
                "product": "5770SS1",
              }
          register: add_single_ptf_records_result

        - name: Task display_add_single_ptf_records_result
          ansible.builtin.debug:
            msg: "{{ add_single_ptf_records_result }}"

        - name: Task query_single_ptf_records_2
          ibm.power_ibmi.ibmi_fix_repo:
            action: "find"
            type: "single_ptf"
            parameters:
              - { "ptf_id": "SI67955" }
              - { "ptf_id": "MF65472" }
              - { "ptf_id": "SI71806" }
          register: query_single_ptf_records_result_2

        - name: Task display_query_single_ptf_records_result_2
          ansible.builtin.debug:
            msg: "{{ query_single_ptf_records_result_2 }}"

      always:
        - name: Task run_sql_to_drop_the_table
          ibm.power_ibmi.ibmi_fix_repo:
            action: "clear"
            type: "single_ptf"
