# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# ibmi-fix-check.yml
# Provide examples on the use of ibmi_fix_check
---
- name: Example playbook on the use of ibmi_fix_check
  hosts: all
  gather_facts: false

  tasks:
    - name: Task query_two_ptf
      ibm.power_ibmi.ibmi_fix_check:
        ptfs:
          - "SI71691"
          - "SI74112"
      register: two_ptf

    - name: Task display_two_ptf
      ansible.builtin.debug:
        msg: "{{ two_ptf }}"

    - name: Task deep_search_ptf
      ibm.power_ibmi.ibmi_fix_check:
        ptfs:
          - "SI63115"
        expanded_requisites: true
      register: deep_search_ptf

    - name: Task display_deep_search_ptf
      ansible.builtin.debug:
        msg: "{{ deep_search_ptf }}"

    - name: Task query_a_single_group
      ibm.power_ibmi.ibmi_fix_check:
        groups:
          - "SF99713"
      register: single_group

    - name: Task display_a_single_group
      ansible.builtin.debug:
        msg: "{{ single_group }}"

    - name: Task query_a_group_and_a_cum
      ibm.power_ibmi.ibmi_fix_check:
        groups:
          - "SF99738"
          - "SF99740"
      register: a_group_and_a_cum

    - name: Task display_a_group_and_a_cum
      ansible.builtin.debug:
        msg: "{{ a_group_and_a_cum }}"
