# Copyright (c) IBM Corporation 2024
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- name: Playbook to install OpenSource utils
  hosts: all
  gather_facts: false

  tasks:
    - name: Create two links to be able to use YUM on IBM i
      ansible.builtin.file:
        src: "/QOpenSys/pkgs/bin/{{ item.src }}"
        dest: "/usr/bin/{{ item.dest }}"
        state: link
      loop:
        - { src: python2, dest: python }
        - { src: yum, dest: yum }

    - name: Install useful OSS utils for IBM i PASE
      # The yum module is removed from Ansible core with version 2.17, so use the raw module to invoke yum until the dnf package arrives for IBM i.
      ansible.builtin.raw: /QOpenSys/pkgs/bin/yum install
                              less
                              rsync
                              ibmichroot
                              ncdu
                              chsh
                              mc
                              curl
                              wget
                              p7zip
                              jq
                              logrotate
                              tmux
                              bash
                              nano
                              -y
      changed_when: true
