# Copyright (c) IBM Corporation 2019, 2021
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- name: Playbook to install dependencies for fix repo
  hosts: all
  gather_facts: true

  tasks:
    - name: Install dependencies if the repo system is an OS400 system
      ansible.builtin.command: '/QOpensys/pkgs/bin/yum install sqlite3 python3-paramiko -y'    # noqa: command-instead-of-module
      # Unable to use ansible.builtin.yum (only for python2) and dnf (for python3) is not yet on IBM i PASE
      when: ansible_os_family.upper() == 'OS400'
      changed_when: ansible_os_family.upper() == 'OS400'

    - name: Install paramiko on other OS
      ansible.builtin.command: pip3 install paramiko -y
      when: ansible_os_family.upper() != 'OS400'
      changed_when: ansible_os_family.upper() != 'OS400'
